# Generated by Django 2.0.5 on 2018-06-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('points', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MainModel',
        ),
    ]
